# Vorweg wurde eine freie Cloud Mongo DB erstellt
name: Website Deployment
on:
  push:
    branches:
      - main
      - dev
# Hier werden globale env Variablen über alle Jobs definiert
env:
    MONGODB_DB_NAME: gha-demo
jobs:
    test:
        # env Variablen werden nur in diesem Job benutzt
        # Die Variablen werden hier als secret gesetzt
        # https://github.com/joergbeicht/gh-env/settings/secrets/actions
        # secrets ist wieder ein Context Object
        # ACHTUNG bzgl. secrets:
        # Wenn wir z.B. mehr als eine DB haben mit unterscheidlichen 
        # MONGODMONGODB_CLUSTER_ADDRESS, MONGODB_USERNAME und MONGODB_PASSWORD
        # dann müssen wir unterschiedliche secrets erstellen also z.B.
        # secrets.MONGODB_USERNAME_TEST, secrets.MONGODB_PASSWORD_TEST und
        # secrets.MONGODB_USERNAME_PROD, secrets.MONGODB_PASSWORD_PROD usw.
        # LÖSUNG Environments 
        # dann kann secrets.MONGODB_USERNAME und secrets.MONGODB_PASSWORD 
        # als eine Variable genutzt werden
        # Erstellt in Evoironments https://github.com/joergbeicht/gh-env/settings/environments
        # ein environment mit dem Namen testing
        # environment: testing
        # dann nutzt der job automatisch die secrets des Environment!
        # Hinweis: Die kostenlose Nutzung der mongo db ist abgelaufen.
        # Das sit aber kein grosses Problem, da die DB nicht benötigt wird um das Bespiel
        # zu verstehen
        env:
            MONGODMONGODB_CLUSTER_ADDRESS: cluster0.ip13jd1.mongodb.net
            MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
            PORT: 8080
        runs-on: ubuntu-latest
        steps:
          - name: Get code
            uses: actions/checkout@v3
          - name: Cache dependencies
            uses: actions/cache@v3
            with:
              path: ~/.npm
              key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
          - name: Install dependencies
            run: npm ci
          # Hier MUSS zuerst ein Webserver gestartet werden damit die test laufen können! 
          # Und der Port obern als Env-Variable gesetzt
          # Die Syntax kann unterschiedlich sein auf mac, windows, linux, ...          
          # Wir nutzen eine Linux Maschinedeswegen runs-on: ubuntu-latest deswegen $PORT
          - name: Run server
            run: npm start & npx wait-on http://127.0.0.1:$PORT
          - name: Run tests
            run: npm test
          - name: Output information
            # {{ env.MONGODB_USERNAME }} das ist eine andere Variante einer env-Variable
            # DU kannst auch $PORT benutzen beide Varianten sind möglich
            run: | 
                echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Output information
              run: |
                echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"